apiVersion: v1
data:
  WebHookSecretKey: OTg3NmJiOTFkNDc5ZjRhMw==
kind: Secret
metadata:
  labels:
    app: qotd-nodejs
    app.kubernetes.io/component: qotd-nodejs
    app.kubernetes.io/instance: qotd-nodejs
    app.kubernetes.io/name: qotd-nodejs
    app.kubernetes.io/part-of: qotd
  name: qotd-nodejs-generic-webhook-secret
type: Opaque
